name: rcvd
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - av=8.0.3
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - ceres-solver=2.0.0
  - certifi=2021.5.30
  - cudatoolkit=11.0.221
  - dataclasses=0.8
  - eigen=3.3.9
  - freetype=2.10.4
  - gflags=2.2.2
  - glog=0.4.0
  - gmp=6.2.1
  - gnutls=3.6.13
  - gtest=1.10.0
  - intel-openmp=2021.3.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=11.1.0
  - libgfortran5=11.1.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - metis=5.1.0
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - mpfr=4.1.0
  - ncurses=6.2
  - nettle=3.6
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - pillow=8.3.1
  - pip=21.0.1
  - pybind11=2.7.1
  - pybind11-global=2.7.1
  - python=3.6.13
  - python_abi=3.6
  - pytorch=1.7.1
  - readline=8.1
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - suitesparse=5.10.1
  - tbb=2020.2
  - tk=8.6.10
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - typing_extensions=3.10.0.0
  - wheel=0.37.0
  - x264=1!161.3030
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - absl-py==0.13.0
    - addict==2.4.0
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - attr==0.3.1
    - backcall==0.2.0
    - beautifulsoup4==4.10.0
    - black==21.4b2
    - cached-property==1.5.2
    - cachetools==4.2.2
    - charset-normalizer==2.0.4
    - click==8.0.1
    - cloudpickle==1.6.0
    - colorama==0.4.4
    - cycler==0.10.0
    - cython==0.29.24
    - decorator==4.4.2
    - detectron2==0.5+cu110
    - einops==0.3.2
    - entrypoints==0.3
    - ffmpeg==1.4
    - ffmpy==0.3.0
    - filelock==3.3.1
    - future==0.18.2
    - fvcore==0.1.5
    - gdown==4.1.1
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.5
    - grpcio==1.39.0
    - h5py==3.1.0
    - hydra-core==1.1.1
    - idna==3.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.5
    - importlib-metadata==4.8.1
    - importlib-resources==5.2.2
    - imutils==0.5.4
    - iopath==0.1.8
    - ipykernel==5.5.5
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jupyter-client==7.0.2
    - jupyter-core==4.7.1
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - matplotlib==3.3.4
    - mmcls==0.23.1
    - mmcv-full==1.2.7
    - moviepy==1.0.3
    - mypy-extensions==0.4.3
    - nest-asyncio==1.5.1
    - networkx==2.5.1
    - oauthlib==3.1.1
    - omegaconf==2.1.1
    - opencv-contrib-python==3.4.2.16
    - opencv-python==4.5.3.56
    - packaging==21.3
    - parso==0.8.2
    - pathspec==0.9.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - portalocker==2.3.2
    - prettytable==2.5.0
    - proglog==0.1.9
    - prompt-toolkit==3.0.20
    - protobuf==3.17.3
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.2
    - pydot==1.4.2
    - pygments==2.10.0
    - pyparsing==2.4.7
    - pypng==0.0.21
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - pyzmq==22.2.1
    - regex==2021.8.28
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scenedetect==0.6.0.3
    - scikit-image==0.17.2
    - scipy==1.5.4
    - setproctitle==1.2.2
    - soupsieve==2.2.1
    - tabulate==0.8.9
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.4
    - termcolor==1.1.0
    - tifffile==2020.9.3
    - timm==0.4.5
    - toml==0.10.2
    - tornado==6.1
    - tqdm==4.62.2
    - traitlets==4.3.3
    - typed-ast==1.4.3
    - urllib3==1.26.6
    - wcwidth==0.2.5
    - werkzeug==2.0.1
    - wget==3.2
    - yacs==0.1.8
    - yapf==0.32.0
    - zipp==3.5.0
